# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: spring-boot-config
#   namespace: backend
# data:
#   spring.datasource.url: "jdbc:postgresql://cnpg-cluster-rw.cnpg-cluster.svc.cluster.local:5432/test"
#   spring.jpa.show-sql: "true"
#   spring.jpa.hibernate.ddl-auto: "update"
#   spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#   server.port: "8080"
#   spring.servlet.multipart.max-file-size: "6MB"
#   spring.servlet.multipart.max-request-size: "6MB"
#   spring.security.basic.enabled: "true"
