apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  username: dGVzdA==
  password: eFZVd1FtYnBibUcwZDdjRlFVdEh4Sk14VDMwSTFXNUc3SHBNOUdwck1IYWl0Z0I5UW90aWFLWTN5cE9LYmhadQ==
metadata:
  name: postgres-secret
  namespace: cnpg-cluster
