apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson  
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: secret/docker-registry-credentials
        property: dockerconfigjson
